services:
  swedeb_api_staging:
    image: "swedeb-api-staging:staging"
    container_name: "swedeb-api-staging"
    restart: always
    ports:
      - "10443:8092"
    env_file:
      - .env
    environment:
      # - SWEDEB_ENVIRONMENT=staging
      # - SWEDEB_BACKEND_TAG=0.2.3
      # - SWEDEB_FRONTEND_TAG=main
      # - SWEDEB_IMAGE_NAME=swedeb-api
      # - SWEDEB_CONTAINER_NAME=swedeb-api
      # - SWEDEB_IMAGE_TAG=staging
      # - SWEDEB_PORT=8092
      # - SWEDEB_HOST_PORT=10443
      # - SWEDEB_SUBNET=172.34.0.0/16
      - SWEDEB_DATA_FOLDER=/data/swedeb/v1.1.0
      - SWEDEB_CONFIG_PATH=/app/config/config.yml
    volumes:
      - "/data/swedeb/v1.1.0:/data"
    networks:
      - swedeb_network_staging

networks:
  swedeb_network_staging:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "72.34.0.0/16"