services:
  swedeb_api:
    image: "${SWEDEB_IMAGE_NAME:-swedeb-api}:${SWEDEB_IMAGE_TAG}"
    container_name: "${SWEDEB_CONTAINER_NAME}-${SWEDEB_ENVIRONMENT}"
    restart: always
    ports:
      - "${SWEDEB_HOST_PORT}:${SWEDEB_PORT}"
    env_file:
      - .env
    environment:
      - SWEDEB_CONFIG_PATH=${SWEDEB_CONFIG_PATH}
      - SWEDEB_DATA_FOLDER=${SWEDEB_DATA_FOLDER}
    volumes:
      - "${SWEDEB_DATA_FOLDER}:/data"
    networks:
      - swedeb_network

networks:
  swedeb_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "${SWEDEB_SUBNET}"