version: '3.8'
services:
  swedeb_api:
    image: "${SWEDEB_IMAGE_NAME:-swedeb-api}:${SWEDEB_IMAGE_TAG:-latest}"
    restart: always
    ports:
      - "${HOST_SWEDEB_PORT}:${SWEDEB_PORT}"
    env_file:
      - .env
    environment:
      - SWEDEB_CONFIG_PATH=${SWEDEB_CONFIG_PATH}
      - SWEDEB_DATA_FOLDER=${SWEDEB_DATA_FOLDER}
      - LANG=C.UTF-8
      - DEBIAN_FRONTEND=noninteractive
      # - LD_LIBRARY_PATH=/usr/local/lib
    volumes:
      - "${SWEDEB_DATA_FOLDER}:/data"
    networks:
      - swedeb_network

networks:
  swedeb_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.33.0.0/16