name: Release Backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    name: Build, Version, and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write      # to push tags and update changelog/pyproject.toml
      packages: write      # to push to ghcr.io

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Required for semantic-release to analyze history and push back
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
  
      - name: Install Python build tools
        run: pipx install poetry

      - name: Install semantic-release using project setup
        run: npm ci

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # - name: Install semantic-release and its plugins (done above via npm ci)
      #   run: npm install semantic-release @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/changelog @semantic-release/git @semantic-release/github @semantic-release/exec

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # These are used by the publish-docker.sh script
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release